# Generated by Django 3.0.5 on 2020-04-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='credit',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='debit',
        ),
    ]
